### ISSUE TITLE
Error: no commands defined in the "fse" namespace if missing .env

### ISSUE THREAD

**Issue by andronocean** [roots/acorn-fse-helper#6]
### Version

1.0.0

### What did you expect to happen?

I thought I'd play with this on a fresh Sage install, but I quickly ran into trouble. I installed Sage on a new, local Laravel Valet site with `composer create-project roots/sage`, then  added Acorn with `composer require roots/acorn`. The Sage theme was activated and displayed correctly.

At that point, I assumed I was ready to run `wp acorn fse:init`.

### What actually happens?

Instead I got this message after running `wp acorn fse:init`:
```
   ERROR  There are no commands defined in the "fse" namespace.  
```
That was weird, since other `acorn` commands were running perfectly.

### Finding the solution
After clearing cache, restarting valet, adding `--debug`, and feeling very confused, I dug deeper into the code and noticed that the `boot()` method of `AcornFseHelperServiceProvider` checks for `$this->app->isProduction()` and skips loading the command if it's a production environment.

I hadn't thought to create an .env file for the theme (in my real projects Bedrock's usually responsible for that).

Once I added the following .env file the command worked perfectly:
```
WP_ENV="development"
```
It makes sense to only allow this in development environments, but it would really be good to mention in the setup instructions that WP_ENV has to be set to something other than production.

A more instructive error message would also be good!

### Steps to reproduce

Set up Sage with Acorn installed at the theme composer level, and do not create an .env file (or have WP_ENV="production").

Then switch WP_ENV to `development` and watch it work.

### System info

N/A

### Log output

```shell
N/A
```

### Please confirm this isn't a support request.

Yes

**Comment by Log1x** [comment]
Hey, sorry about that. I adjusted this behavior in #7 and pushed a release.

**Comment by andronocean** [comment]
So much better! Thank you.
